### ISSUE TITLE
Change License to BSD?

### ISSUE THREAD

**Issue by chrbertsch** [BasilioPV/ShipSIM#1]
Please consider changing the License to the BSD license, that is now also used for the Modelica standard library.

Reason: The BSD license is often used, well known to legal departments and often white-listed for use in companies or other organizations.
On the other hand, the "Modelica License 2 with additional clause 16" is not well known, requires special check by legal departments and thus might hinder the usage.
That is the reason, why e.g. the MSL also changed from the "Modelica 2 License" to BSD license, https://github.com/modelica/ModelicaStandardLibrary/blob/master/LICENSE, and the BSD license is also required e.g. for applications for the Library award at the next Modelica Conference (https://2023.international.conference.modelica.org/call2023.html), where I would encourage you to apply, as this is a really interesting new application domain for Modelica)

**Comment by BasilioPV** [comment]
Hi Christian! Regarding the license, we want the following (in natural words): 
- Freedom to use, modify and ditribute. Unless for the derived work, the user cannot charge fees.
- Mandatory citation to the library on the above cases (we seek recognition for our work)
- If anyone produces public material (paper, presentation, work shown in their webpage, etc...) using the library, we want the rights of use of this public material as reference in our presentations to promote the library.

We have seen the reccomended Modelica License 2 on Modelica Association web. After revised, we have the need to add a last clause for the third point above. This is the reason for use this license. 

But your point of vision is right, the use of a non-standard license will produce rejection on the companies.
I will review the BSD license and revert to you the decission.

Thank you for encouraging me to present a publication in the 15th Modelica Conference!

**Comment by BasilioPV** [comment]
Since Version 1.1.0 the license in changed to 3-Clause BSD.

**Comment by thorade** [comment]
Here are two related links:

- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

If the license file follows the right structure, the license will also be displayed in the side panel, see e.g. the Modelica standard library:
https://github.com/modelica/ModelicaStandardLibrary

<img width="256" alt="image" src="https://user-images.githubusercontent.com/314571/229080145-4934636f-1753-4508-bc6d-7e80deae889c.png">

**Comment by BasilioPV** [comment]
Ok, done.
