### ISSUE TITLE
Invalid extends of icon

### ISSUE THREAD

**Issue by maltelenz** [BasilioPV/ShipSIM#2]
Here:

https://github.com/BasilioPV/ShipSIM/blob/3d5f3a84ce2961fe4eca0b3091394d4828127c95/ShipSIM.mo#L984-L985

A `function` extends a `package`, which is not legal Modelica.

You probably intended to extend `Modelica.Icons.Function`?

The same thing exists in `ShipSIM.Functions.NACA0018`.

**Comment by BasilioPV** [comment]
Hi Malte,
Thanks for your contribution, you are right, the intention is to extend .Function icon.
This is solved in the code
Thanks!

**Comment by maltelenz** [comment]
Looks good now, thanks for the quick fix!
