### ISSUE TITLE
Unbalanced connector

### ISSUE THREAD

**Issue by maltelenz** [BasilioPV/ShipSIM#3]
`ShipSIM.Interfaces.ShipData` has 14 potential signals but no flow signals. This is not legal Modelica, see https://specification.modelica.org/maint/3.6/connectors-and-connections.html#balancing-restriction-and-size-of-connectors

> For each non-partial non-expandable connector class the number of flow variables shall be equal to the number of variables that are neither parameter, constant, input, output, stream nor flow.

Maybe it can be solved with some `input` and `output` prefixes, since it looks like these are intended to be directional?

**Comment by BasilioPV** [comment]
Hi Malte,
Thanks for your feedback. I have produced two connectors with input and output prefixes. I think that is solved now.

**Comment by maltelenz** [comment]
Looks like legal Modelica now!
